apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: cvenegas
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 80
      targetPort: 8080